[package]
name = "dlg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.9.0"
common_macros = "0.1.1"        # TODO: remove this by sections macro
logos = "0.12.1"
