name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose
    - name: Test
      run: cargo test --verbose
    - name: Build for Linux
      run: cargo build -p dlg-debugger --release
    - name: Install target for Windows
      run: rustup target add x86_64-pc-windows-msvc
    - name: Build for Windows
      run: cargo build -p dlg-debugger --release --target=x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v3
      with:
        name: ubuntu-dlg-debugger
        path: |
          target/release/dlg-debugger
          target/release/dlg-debugger.exe
