name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose
    - name: Test
      run: cargo test --verbose
    - name: Prepare for building
      run: |
        sudo apt install mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Build artifacts
      run: |
        cargo build -p dlg-debugger --release
        cargo build -p dlg-debugger --release --target=x86_64-pc-windows-gnu
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/release/dlg-debugger
          target/release/dlg-debugger.exe
